### ISSUE TITLE
SSL error with python requests session

### ISSUE THREAD

**Issue by rikko215** [sjkingo/python-freshdesk#15]
Hi, I would like to ask you some favor.I am trying to solve ssl error from a python login source code and still don't know how to solve this issue.

■environment
Python 3.5.2
requests -the latest version

■source code
```
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# login username and password
USER = "JS-TESTER"
PASS = "ipCU12ySxI"

# session starts
session = requests.session()

# login information
login_info = {
    "username_mmlbbs6": USER,  
    "password_mmlbbs6": PASS,  
    "back": "index.php",       
    "mml_id": "0"             
}
url_login = "http://uta.pw/sakusibbs/users.php?action=login&m=try"
res = session.post(url_login, data=login_info)
res.raise_for_status() 

# pick up mypage's url
soup = BeautifulSoup(res.text, "html.parser")
a = soup.select_one(".islogin a")
if a is None:
    print("Couldn't load mypage data")
    quit()
# Convert the relative URL to an absolute URL
url_mypage = urljoin(url_login, a.attrs["href"])
print("マイページ=", url_mypage)

# Access mypage
res = session.get(url_mypage)
res.raise_for_status()

# List up favorite titles
soup = BeautifulSoup(res.text, "html.parser")
links = soup.select("#favlist li > a")
for a in links:
    href = a.attrs["href"]
    title = a.get_text()
    print("-", title, ">", href)
```

■error details
```
[vagrant@localhost ch2]$ python login-getfav.py 
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uta.pw', port=443): Max retries exceeded with url: /sakusibbs/users.php?action=login&m=try (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "login-getfav.py", line 21, in <module>
    res = session.post(url_login, data=login_info)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='uta.pw', port=443): Max retries exceeded with url: /sakusibbs/users.php?action=login&m=try (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

```

■hypothesis
In other source code I have tried to change requests get method as follows(verify=False) and it worked. I wonder if I can apply this to session method too? is so, where should I put verify=False... 
```
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# login username and password
USER = "JS-TESTER"
PASS = "ipCU12ySxI"

# session starts
session = requests.session()

# login information
login_info = {
    "username_mmlbbs6": USER,  
    "password_mmlbbs6": PASS,  
    "back": "index.php",       
    "mml_id": "0"             
}
url_login = "http://uta.pw/sakusibbs/users.php?action=login&m=try"
res = session.post(url_login, data=login_info, verify=False)
res.raise_for_status() 

# pick up mypage's url
soup = BeautifulSoup(res.text, "html.parser")
a = soup.select_one(".islogin a")
if a is None:
    print("Couldn't load mypage data")
    quit()
# Convert the relative URL to an absolute URL
url_mypage = urljoin(url_login, a.attrs["href"])
print("マイページ=", url_mypage)

# Access mypage
res = session.get(url_mypage)
res.raise_for_status()

# List up favorite titles
soup = BeautifulSoup(res.text, "html.parser")
links = soup.select("#favlist li > a")
for a in links:
    href = a.attrs["href"]
    title = a.get_text()
    print("-", title, ">", href)
```

■error details
```
[vagrant@localhost ch2]$ python login-getfav.py 
/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Couldn't load mypage data
```

**Comment by sjkingo** [comment]
Sorry, this doesn't have anything to do with this project. I hope you've sorted the issue out.
